### ISSUE TITLE
Consider switching to RST

### ISSUE THREAD

**Issue by johndgiese** [innolitics/rdm#62]
Questions:

- [ ] How much code/features can we remove if we use RST?
- [ ] Can we remove the `rdm tex` command completely?
- [ ] Can we remove our auto numbering support?
- [ ] Is the pandoc rst to docx conversion good enough that we don't need any docx customization?
- [ ] What are the downsides of using RST?

**Comment by orwonthe** [comment]
I used `pandoc` to convert our release *.md files to *.rst. This was to mimic having written them in RST in the first place. I then used `pandoc` to convert those markdown files into DOCX files. This mostly worked but failed with images. But this turned out to be a false result. It turns out that `pandoc` was using the RST `figure` command for the images. If I hand edited those to use the RST `image` command, then I had no problems.

Conclusion: We do not lose ground using RST

**Comment by orwonthe** [comment]
I am not able to get auto numbering to work in RST. This does not necessarily mean it is not possible, just that I have not got it working.

**Comment by orwonthe** [comment]
If we change to RST:
We will still need the `rdm render` command. We will not need `rdm tex`. We will still need to handle images, changing base references and translating SVG. The SVG --> PDF translation needs to be changed to SVG --> PNG. We need to use `Sphinx` instead of `pandoc`.  There is an extension, `docxbuilder`, that does a superior job of creating `docx` files. We can remove our auto numbering support. The Sphinx system has plenty of hooks and options for getting a desired style, headers, footers, etc that we will not need any special docx support beyond providing good starting options.

Changing to RST is about a one week project:
1. Use `pandoc` to translate current templates to RST.
2. Edit those templates to include section numbering and table of contents, maybe an index.
3. Create a new `Makefile` using `Sphinx`.
4. Create good starting style options.
5. Modify the image filters to parse for RST syntax instead of current syntax.
6. Update the documentation, especially the tools required.

Downside:
A. Work listed above.
B. There will be some engineers that know markdown and will need to learn RST (balanced by the converse).

To my knowledge there are no markdown features we are using that do not have RST equivalents.

**Comment by johndgiese** [comment]
Thanks for the update, this is good news! It sounds like Sphinx is a good option for us.

Regarding:

> We will not need rdm tex.

Does this mean all of the features:

https://github.com/innolitics/rdm/blob/master/rdm/tex.py#L25-L28

Will be possible to configure with RST out of the box? E.g., I know that margins can be controlled using the pandoc commandline. And I think RST supports headers and footers on the PDF pages. (Also, maybe we can test header and footer support with the DOCX files as well)

**Comment by johndgiese** [comment]
A few other things that would be very useful to have are:

1. The ability to refer to particular sections in the RST without knowing the section number. E.g., if we could say "see Section `section label`_" (or whatever the RST syntax is for such references).

2. The ability to produce Figures that have captures, and to be able to refer to figure numbers in the text without knowing the number beforehand.

Both of these would be tough to do with markdown and were some of the reasons why I was hoping to switch to RST. If we can accomplish both of them, that would certainly strengthen the argument for switching to RST in my mind.

**Comment by orwonthe** [comment]
Sphinx presents another opportunity. We could structure `rdm` as a Sphinx extension. It has a well documented API. We would be leveraging Sphinx to do the parsing and building while inserting the `rdm` specific activity we need.
https://www.sphinx-doc.org/en/master/extdev/index.html#dev-extensions

**Comment by johndgiese** [comment]
Sphinx supports RST and MD: https://www.sphinx-doc.org/en/master/usage/markdown.html

**Comment by johndgiese** [comment]
Sphinx also has jinja2 templating, although it's not clear whether this applies only to the HTML output, or if it applies to all document types.

Thought: sphinx is used to document a variety of software projects. Thus, it seems likely that it will fit the user needs for doing this. What is less clear is whether RDM has other userneeds that won't be met, or may even come into conflict with, these user needs. To explore this, I think we need to write out the user needs for RDM itself.

**Comment by johndgiese** [comment]
After some further thought about this, I think using pandoc in place of `rdm tex` will be able to solve most of our problems. Pandoc's version of markdown has a good bit of support.

Sphinx seems like it's overkill in some ways and it's meant for a different use case. Thus, I suspect we'll run into various issues once we go down that route.
