### ISSUE TITLE
Top down meeting changes into existing init projects.

### ISSUE THREAD

**Issue by MALathon** [innolitics/rdm#83]
I'm  looking for a workflow that merges changes to the template source down into existing projects that were generated from the templates.

For example, if I have multiple projects that used the software plan template, and I made a global change to the template because of a change in 62304, I'd like some way of automating a regression analysis to flag each project and evaluate if the change is applicable.

My guess is I would need to create a much larger project management system around this, but I was wondering if you already had this workflow or any ideas or existing packages that could do this.

**Comment by johndgiese** [comment]
There is a straight forward way to handle this need within RDM. Since RDM uses the Jinja templating language and Jinja supports [template inheritance](https://jinja.palletsprojects.com/en/3.0.x/templates/#template-inheritance), you use a base template as your global plan and you could then inherit from this base template in each project---overriding parts that aren't applicable.
